name: Deploy to GCP

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Build and push the container image
      - name: Build and push container
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: gcr.io/${{ env.PROJECT_ID }}/rest-api:${{ github.sha }}
      
      # Deploy the container image to Cloud Run
      - name: Deploy to Cloud Run
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      run: |
        gcloud run deploy rest-server \
          --image=gcr.io/${{ env.PROJECT_ID }}/rest-api:${{ github.sha }} \
          --region=us-central1
